#! /bin/sh

# Workaround to improve network performance
# sudo iwconfig wlan0 txpower 10dBm

# Polybar
# /home/gg/.config/polybar/launch.sh &

# Italian keyboard
setxkbmap it

# High-dpi settings
xrandr --dpi 192
xrdb -merge $HOME/.Xresources

# Top bar
# slstatus 2> /dev/null &

# Lock screen after 10 minutes
# xautolock -time 10 -locker slock

# Pywal restore
wal -R

# Natural scrolling
xinput --set-prop "Apple SPI Touchpad" "libinput Natural Scrolling Enabled" 1
xinput --set-prop "Apple SPI Touchpad" "libinput Accel Speed" +0.5

# Wallpaper
# nitrogen --restore &

# Picom for smooth transitions
picom -Cb

# Window manager
exec spectrwm 2> /tmp/spectrwm.log
